### ISSUE TITLE
Errors upon build

### ISSUE THREAD

**Issue by AppreciateIT** [ultratrail/generator-jhipster-leafletmap#1]
I'm getting the following errors on maven build after using the generator-jhipster-leafletmap v1.0.5: 
"ERROR in src/main/webapp/app/pages/leaflet/map.component.html(1,422): : Property 'maps' does not exist on type 'MapComponent'.
[INFO] src/main/webapp/app/pages/leaflet/map.component.html(1,306): : Property 'onMapReady' does not exist on type 'MapComponent'."

When I look at the map.component.html there are * in front of the ngIf and ngFor.

**Comment by HugoSecteur4** [comment]
This generator is made to work with applications generated with the latest version of JHipster (with angular 5 and TypeScript, not with AngularJS). 

If this is your case, can you please send me your application by email so I can see where the problem is. gdahugo@gmail.com

**Comment by AppreciateIT** [comment]
It is Angular 5 and Typescript.  Not sure if i can email it to you.  May be something unrelated to your module.  Building on a MacBook, but dockerizing the app.  Will update you after I try again.

**Comment by AppreciateIT** [comment]
Should I be running this generator before dockerizing with "./mvnw package -Pprod dockerfile:build -e" Or after and logging into the terminal on the docker image? (headscratch)

**Comment by AppreciateIT** [comment]
I'm still getting this issue.  Something's wrong or there's a step missing.  I keep getting this error on build:  
"**ERROR in src/main/webapp/app/pages/leaflet/map.component.html(1,433): : Property 'maps' does not exist on type 'MapComponent'.
[INFO] src/main/webapp/app/pages/leaflet/map.component.html(1,306): : Property 'onMapReady' does not exist on type 'MapComponent'.**"
